export const SEARCH_CITY = 'SEARCH_CITY';
export const SEARCH_CITY_SUCCESS = 'SEARCH_CITY_SUCCESS';
export const SEARCH_CITY_FAIL = 'SEARCH_CITY_FAIL';

export const GET_WEATHER_BY_WOEID = 'GET_WEATHER_BY_WOEID';
export const GET_WEATHER_BY_WOEID_SUCCESS = 'GET_WEATHER_BY_WOEID_SUCCESS';
export const GET_WEATHER_BY_WOEID_FAIL = 'GET_WEATHER_BY_WOEID_FAIL';
